# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 300

# Joint Trajectory Controller
arm140_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.1, goal: 0.1}
    joint_2: {trajectory: 0.1, goal: 0.1}
    joint_3: {trajectory: 0.1, goal: 0.1}
    joint_4: {trajectory: 0.1, goal: 0.1}
    joint_5: {trajectory: 0.1, goal: 0.1}
    joint_6: {trajectory: 0.1, goal: 0.1}
  
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

controller_list:
  - name: arm140_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6